baseURL = 'https://f.actor'
languageCode = 'en-us'
title = 'Factor' 
theme = 'cactus'

# Main menu which appears below site header.
[[menu.main]]
name = "About"
url = "/"
weight = 1

[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 2

[[menu.main]]
name = "Team"
url = "#team"
weight = 3

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
name = "github"
link = "https://github.com/factorcrypto"
[[params.social]]
name = "twitter"
link = "https://www.twitter.com"
[[params.social]]
name = "email"
link = "hello@f.actor"  # no need for "mailto:" in the head

[params]
    # Overall
    colortheme = "white" # light, white, or classic
    copyright = "Factor"
    mathjax = true

    # Home
    description = "Factor builds and invests in open internet infrastructure that enhances privacy, trust, and financial access."
    mainSection = "posts" # your main section
    postsOnHomePage = 20 # this option will be ignored if showAllPostsOnHomePage is set to true
    dateFormat = "2006-01-02" # default

    # Home::Projects
    showProjectsList = true # show projects list by default (if projects data file exists).

    # Posts
    tocInline = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4